[hewg]
version = "0.4.0-alpha"
type = "library"

[project]
version = "0.1.0"
org = "crow"
name = "chirp-interpret"
description = "core interpreter of the chirp language"
authors = { }

[depends]
internal = { }
external = { }

[cxx]
flags = { "-Wall" "-Wextra" "-Werror" }
std = 23
sources = { }

[c]
flags = { "-Wall" "-Wextra" "-Werror" }
std = 17
sources = {
	"chirp.c"
}

[hooks.prebuild]
[hooks.postbuild]
